"""Added use_colors boolean to users

Revision ID: 1095b92e3a4
Revises: 682f16031f
Create Date: 2015-11-29 15:44:47.153635

"""

# revision identifiers, used by Alembic.
revision = '1095b92e3a4'
down_revision = '682f16031f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    op.add_column('users', sa.Column('use_colors', sa.Boolean(),
        nullable=False, default=True, server_default='true'))


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'use_colors')
    ### end Alembic commands ###
