"""Inital migration

Revision ID: 1b64df25658
Revises: None
Create Date: 2015-07-25 00:31:13.182750

"""

# revision identifiers, used by Alembic.
revision = '1b64df25658'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entry_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entry_field_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=300), nullable=True),
    sa.Column('entry_id', sa.Integer(), nullable=True),
    sa.Column('entry_field_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entry_field_id'], ['entry_fields.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entry_field_answers')
    op.drop_table('entry_fields')
    op.drop_table('entries')
    ### end Alembic commands ###
