---

- name: server setup
  hosts: servers
  remote_user: root

  vars:
    - admin_email: admin@mooddiary.org
    - nginx_vhosts:
      - mooddiary
      - councilofcode

  roles:
    - role: common
    - role: ssl
    - role: nginx
    - role: postgres
    - role: uwsgi
    - role: tools
    - role: mail